language: c

sudo: required

global:
  env:
    - R_BUILD_ARGS="--no-manual"
    - R_CHECK_ARGS="--no-manual --as-cran"

# For testing against and using RcppRedis
services:
  - redis-server

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh install_aptget libhiredis-dev
  - ./travis-tool.sh install_deps
  - ./travis-tool.sh install_r RcppRedis

script:
  - ./travis-tool.sh run_tests
  - ./extra/revdep.R

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
